"""UT (Unita di Tracciamento) record — matches the classic pyarchinit ut_table."""
from sqlalchemy import Column, Integer, String, Text, Float, Numeric
from .base import BaseModel


class Ut(BaseModel):
    __tablename__ = 'ut_table'
    id_ut = Column(Integer, primary_key=True, autoincrement=True)
    progetto = Column(String(100))
    nr_ut = Column(Integer)
    ut_letterale = Column(String(100))
    def_ut = Column(String(100))
    descrizione_ut = Column(Text)
    interpretazione_ut = Column(String(100))
    nazione = Column(String(100))
    regione = Column(String(100))
    provincia = Column(String(100))
    comune = Column(String(100))
    frazione = Column(String(100))
    localita = Column(String(100))
    indirizzo = Column(String(100))
    nr_civico = Column(String(100))
    carta_topo_igm = Column(String(100))
    carta_ctr = Column(String(100))
    coord_geografiche = Column(String(100))
    coord_piane = Column(String(100))
    quota = Column(Float)
    andamento_terreno_pendenza = Column(String(100))
    utilizzo_suolo_vegetazione = Column(String(100))
    descrizione_empirica_suolo = Column(Text)
    descrizione_luogo = Column(Text)
    metodo_rilievo_e_ricognizione = Column(String(100))
    geometria = Column(String(100))
    bibliografia = Column(Text)
    data = Column(String(100))
    ora_meteo = Column(String(100))
    responsabile = Column(String(100))
    dimensioni_ut = Column(String(100))
    rep_per_mq = Column(String(100))
    rep_datanti = Column(String(100))
    periodo_I = Column(String(100))
    datazione_I = Column(String(100))
    interpretazione_I = Column(String(100))
    periodo_II = Column(String(100))
    datazione_II = Column(String(100))
    interpretazione_II = Column(String(100))
    documentazione = Column(Text)
    enti_tutela_vincoli = Column(String(100))
    indagini_preliminari = Column(String(100))
    visibility_percent = Column(Integer)
    vegetation_coverage = Column(String(255))
    gps_method = Column(String(100))
    coordinate_precision = Column(Float)
    survey_type = Column(String(100))
    surface_condition = Column(String(255))
    accessibility = Column(String(255))
    photo_documentation = Column(Integer)
    weather_conditions = Column(String(255))
    team_members = Column(Text)
    foglio_catastale = Column(String(100))
    potential_score = Column(Numeric(5, 2, asdecimal=False))
    risk_score = Column(Numeric(5, 2, asdecimal=False))
    potential_factors = Column(Text)
    risk_factors = Column(Text)
    analysis_date = Column(String(100))
    analysis_method = Column(String(100))

    def to_dict(self):
        return {c.name: getattr(self, c.name) for c in self.__table__.columns}
